// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDUgjiS_nR_NaKGMvB7E2eeWuXX384MjI',
    appId: '1:894660073199:web:0023bc85d57a52aded6d1a',
    messagingSenderId: '894660073199',
    projectId: 'test-49707',
    authDomain: 'test-49707.firebaseapp.com',
    storageBucket: 'test-49707.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnhGlJE83iJPVwTOysXFOJgKlldm58E90',
    appId: '1:894660073199:android:1c52bc2c71f52c7aed6d1a',
    messagingSenderId: '894660073199',
    projectId: 'test-49707',
    storageBucket: 'test-49707.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAItosENPqWITM-1iU4VYGkqH6JVsfgyPQ',
    appId: '1:894660073199:ios:673c439bb377d549ed6d1a',
    messagingSenderId: '894660073199',
    projectId: 'test-49707',
    storageBucket: 'test-49707.appspot.com',
    iosClientId: '894660073199-8l0117epaqtaf4vq7k22q2seki45ico9.apps.googleusercontent.com',
    iosBundleId: 'com.example.sabak33Firebase1',
  );
}
